"""add indexes to CompanyName, CompanyTagName

Revision ID: 05c331d03c35
Revises: 15bcecd43e58
Create Date: 2025-06-03 17:10:31.776011

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "05c331d03c35"
down_revision: Union[str, None] = "15bcecd43e58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_index(
        "ix_company_names_name_exact", "company_names", ["name"], unique=False
    )
    op.create_index(
        "ix_company_names_name_trgm",
        "company_names",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_company_tag_names_name_exact", "company_tag_names", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_company_tag_names_name_exact", table_name="company_tag_names")
    op.drop_index(
        "ix_company_names_name_trgm",
        table_name="company_names",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("ix_company_names_name_exact", table_name="company_names")
    # ### end Alembic commands ###
