"""init company models

Revision ID: 15bcecd43e58
Revises: 
Create Date: 2025-06-02 22:45:40.493649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bcecd43e58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'language_code')
    )
    op.create_index(op.f('ix_company_names_language_code'), 'company_names', ['language_code'], unique=False)
    op.create_table('company_tag',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('company_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['company_tag_id'], ['company_tags.id'], ),
    sa.PrimaryKeyConstraint('company_id', 'company_tag_id')
    )
    op.create_table('company_tag_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_tag_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_tag_id'], ['company_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_tag_id', 'language_code')
    )
    op.create_index(op.f('ix_company_tag_names_language_code'), 'company_tag_names', ['language_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_tag_names_language_code'), table_name='company_tag_names')
    op.drop_table('company_tag_names')
    op.drop_table('company_tag')
    op.drop_index(op.f('ix_company_names_language_code'), table_name='company_names')
    op.drop_table('company_names')
    op.drop_table('company_tags')
    op.drop_table('companies')
    # ### end Alembic commands ###
