"""add unique constraint to names in company models

Revision ID: cdf791bae03d
Revises: 05c331d03c35
Create Date: 2025-06-04 00:12:25.462805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf791bae03d'
down_revision: Union[str, None] = '05c331d03c35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company_names', ['name', 'language_code'])
    op.create_unique_constraint(None, 'company_tag_names', ['name', 'language_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company_tag_names', type_='unique')
    op.drop_constraint(None, 'company_names', type_='unique')
    # ### end Alembic commands ###
